import { ALCALDIA_RIONEGRO_ADDRESS } from "@/lib/rionegro-content";

export type OfficialPlace = {
  name: string;
  category: string;
  address: string;
  area?: string;
  aliases?: string[];
  tags?: string[];
  openingHoursEs?: string;
  openingHoursEn?: string;
};

export const officialPlaces: OfficialPlace[] = [
  {
    name: "Alcaldia de Rionegro (Palacio Municipal)",
    category: "Gobierno",
    address: ALCALDIA_RIONEGRO_ADDRESS,
    aliases: ["alcaldia", "palacio municipal", "city hall", "municipal palace", "town hall"],
    tags: ["citizen_services", "institutional_services", "procedures", "city_hall"],
    openingHoursEs: "Lunes a jueves de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 5:00 p.m.; viernes de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 4:00 p.m.",
    openingHoursEn: "Monday to Thursday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 5:00 p.m.; Friday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 4:00 p.m.",
  },
  {
    name: "Secretaria de Planeacion",
    category: "Gobierno",
    address: "Carrera 50 # 49 - 05, Piso 2",
    aliases: ["planeacion", "planning office", "planning secretariat"],
    tags: ["planning", "institutional_services", "procedures"],
    openingHoursEs: "Horario institucional general: lunes a jueves de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 5:00 p.m.; viernes de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 4:00 p.m.",
    openingHoursEn: "General institutional hours: Monday to Thursday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 5:00 p.m.; Friday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 4:00 p.m.",
  },
  {
    name: "Secretaria de Hacienda",
    category: "Gobierno",
    address: "Carrera 50 # 49 - 05, Piso 3",
    aliases: ["hacienda", "treasury office", "finance office"],
    tags: ["taxes", "institutional_services", "procedures"],
    openingHoursEs: "Horario institucional general: lunes a jueves de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 5:00 p.m.; viernes de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 4:00 p.m.",
    openingHoursEn: "General institutional hours: Monday to Thursday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 5:00 p.m.; Friday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 4:00 p.m.",
  },
  {
    name: "SOMOS (Movilidad y Transito)",
    category: "Gobierno",
    address: "Carrera 48 # 47-19",
    aliases: ["movilidad", "transito", "traffic office", "mobility office"],
    tags: ["mobility", "institutional_services", "procedures"],
    openingHoursEs: "Horario institucional general: lunes a jueves de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 5:00 p.m.; viernes de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 4:00 p.m.",
    openingHoursEn: "General institutional hours: Monday to Thursday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 5:00 p.m.; Friday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 4:00 p.m.",
  },
  {
    name: "Camara de Comercio del Oriente Antioqueno",
    category: "Servicios",
    address: "Calle 51 # 51-57",
    aliases: ["camara de comercio", "chamber of commerce"],
  },
  {
    name: "Edeso (Empresa de Desarrollo Sostenible)",
    category: "Gobierno",
    address: "Carrera 54 # 56-162",
    area: "Via Fontibon",
    aliases: ["edeso", "desarrollo sostenible"],
  },
  {
    name: "ESO (Empresa de Seguridad del Oriente)",
    category: "Seguridad",
    address: "Carrera 46 # 30-425",
    area: "Vereda El Rosal",
    aliases: ["eso", "empresa de seguridad del oriente"],
  },
  {
    name: "IMER (Instituto de Deportes)",
    category: "Deporte",
    address: "Calle 43A # 50-200",
    area: "Unidad Deportiva Ivan Ramiro Cordoba",
    aliases: ["imer", "instituto de deportes"],
  },
  {
    name: "Centro Integral de Bienestar Animal (CEIBA)",
    category: "Servicios",
    address: "Sector El Tablacito",
    aliases: ["ceiba", "bienestar animal", "animal welfare center"],
  },
  {
    name: "Personeria Municipal de Rionegro",
    category: "Gobierno",
    address: "Calle 49 # 50-05",
    area: "Palacio Municipal",
    aliases: ["personeria", "ombudsman office"],
  },
  {
    name: "Casa de la Convencion (Museo y Archivo)",
    category: "Turismo",
    address: "Calle 51 # 47-67",
    aliases: [
      "casa de la convencion",
      "museo y archivo",
      "convention house museum",
      "history museum",
      "historical museum",
      "museo historico",
    ],
  },
  {
    name: "SENA Rionegro",
    category: "Educacion",
    address: "Calle 51 # 47-67",
    area: "Sede Centro",
    aliases: ["sena", "sena rionegro"],
  },
  {
    name: "C.C. San Nicolas",
    category: "Comercio",
    address: "Calle 43 # 54-139",
    area: "Sector El Porvenir",
    aliases: [
      "san nicolas",
      "san nicolas mall",
      "centro comercial san nicolas",
      "mall center san nicolas",
      "shopping center san nicolas",
    ],
  },
  {
    name: "C.C. Savanna Plaza",
    category: "Comercio",
    address: "Carrera 55A # 35-227",
    aliases: ["savanna plaza", "savanna"],
  },
  {
    name: "Complex Llanogrande",
    category: "Comercio",
    address: "Km 8.5 Via Rionegro - Llanogrande",
    aliases: ["complex", "complex llanogrande"],
  },
  {
    name: "Mall Llanogrande",
    category: "Comercio",
    address: "Km 8 Via Llanogrande",
    aliases: ["mall llanogrande", "llanogrande mall"],
  },
  {
    name: "C.C. Reserva Plaza",
    category: "Comercio",
    address: "Transversal 24 # 42-121",
    aliases: ["reserva plaza"],
  },
  {
    name: "Mall Puerto Bulevar",
    category: "Comercio",
    address: "Km 7.5 Via Rionegro - Llanogrande",
    area: "Sector Gualanday",
    aliases: ["puerto bulevar", "mall puerto bulevar"],
  },
  {
    name: "Mall Jardines de Llanogrande",
    category: "Comercio",
    address: "Km 9 Via Llanogrande",
    aliases: ["mall jardines", "jardines de llanogrande"],
  },
  {
    name: "C.C. Plaza Real",
    category: "Comercio",
    address: "Calle 49 # 50-42",
    aliases: ["plaza real"],
  },
  {
    name: "Rio Sur Mall",
    category: "Comercio",
    address: "Sector El Porvenir",
    aliases: ["rio sur mall", "riosur mall"],
  },
  {
    name: "Linares Shopping",
    category: "Comercio",
    address: "Calle 52 con Carrera 50",
    aliases: ["linares shopping", "linares"],
  },
  {
    name: "Parque Recreativo Comfama Tutucan",
    category: "Turismo",
    address: "Calle 20 # 55-465",
    aliases: ["tutucan", "comfama tutucan"],
  },
  {
    name: "Parque Principal (Plaza de la Libertad)",
    category: "Turismo",
    address: "Calle 49 con Carrera 50",
    aliases: ["parque principal", "plaza de la libertad", "main square", "main park"],
  },
  {
    name: "San Antonio de Pereira (Parque Gastronomico)",
    category: "Turismo",
    address: "Carrera 55",
    aliases: ["san antonio de pereira", "gastronomic park"],
  },
  {
    name: "Estadio Alberto Grisales",
    category: "Deporte",
    address: "Carrera 50 # 38-1",
    aliases: ["alberto grisales stadium", "estadio grisales"],
  },
  {
    name: "Coliseo Ivan Ramiro Cordoba",
    category: "Deporte",
    address: "Calle 43A # 50-200",
    aliases: ["coliseo ivan ramiro cordoba", "ivan ramiro cordoba coliseum"],
  },
  {
    name: "Museo de Artes Religiosas",
    category: "Turismo",
    address: "Catedral de San Nicolas",
    aliases: ["museo de artes religiosas", "religious arts museum"],
  },
  {
    name: "Cerro del Viao",
    category: "Turismo",
    address: "Mirador natural",
    area: "Vereda El Rosal",
    aliases: ["cerro del viao", "viao viewpoint"],
  },
  {
    name: "Parque Lineal del Rio Negro",
    category: "Turismo",
    address: "Ribera del rio, sector centro",
    aliases: ["parque lineal", "linear park", "river park"],
  },
  {
    name: "Clinica Somer",
    category: "Salud",
    address: "Calle 38 # 54A-35",
    aliases: ["somer clinic", "somer"],
  },
  {
    name: "Hospital San Juan de Dios (E.S.E.)",
    category: "Salud",
    address: "Carrera 48 # 56-59",
    aliases: ["hospital san juan de dios", "san juan de dios hospital"],
  },
  {
    name: "San Vicente Fundacion (Centros Especializados)",
    category: "Salud",
    address: "Km 2.4 Via Llanogrande",
    aliases: ["san vicente fundacion", "san vicente", "specialized centers"],
  },
  {
    name: "Clinica Sura",
    category: "Salud",
    address: "C.C. San Nicolas",
    aliases: ["clinica sura", "sura clinic"],
  },
  {
    name: "Compania de Bomberos Rionegro",
    category: "Emergencias",
    address: "Calle 52 # 47-52",
    aliases: ["bomberos", "fire department", "fire station"],
  },
  {
    name: "Aeropuerto Internacional Jose Maria Cordova",
    category: "Transporte",
    address: "Via Santa Elena",
    aliases: ["aeropuerto", "airport", "jmc", "jose maria cordova airport"],
  },
  {
    name: "Terminal de Transportes de Rionegro",
    category: "Transporte",
    address: "Calle 46 # 48-18",
    aliases: ["terminal de transportes", "transport terminal", "bus terminal"],
  },
  {
    name: "Zona Franca de Rionegro",
    category: "Logistica",
    address: "Vereda Chachafruto",
    aliases: ["zona franca", "free trade zone"],
  },
  {
    name: "Fiscalia General de la Nacion (Sede Rionegro)",
    category: "Justicia",
    address: "Calle 42 # 55-60",
    aliases: ["fiscalia", "prosecutor office", "district attorney"],
  },
  {
    name: "Notaria Primera de Rionegro",
    category: "Justicia",
    address: "Calle 51 # 48-35",
    aliases: ["notaria primera", "first notary"],
  },
  {
    name: "Notaria Segunda de Rionegro",
    category: "Justicia",
    address: "Carrera 51 # 49-47",
    aliases: ["notaria segunda", "second notary"],
  },
  {
    name: "Registraduria Especial de Rionegro",
    category: "Justicia",
    address: "Calle 50 # 46-24",
    aliases: ["registraduria", "civil registry"],
  },
  {
    name: "Cuerpo Tecnico de Investigacion (CTI)",
    category: "Justicia",
    address: "Diagonal a la Fiscalia",
    aliases: ["cti"],
  },
  {
    name: "Inspeccion de Policia de San Antonio",
    category: "Seguridad",
    address: "Parque de San Antonio de Pereira",
    aliases: ["inspeccion de policia de san antonio"],
  },
  {
    name: "Inspeccion de Policia de Llanogrande",
    category: "Seguridad",
    address: "Sector El Tablazo",
    aliases: ["inspeccion de policia de llanogrande"],
  },
  {
    name: "Comisaria de Familia (Sede El Porvenir)",
    category: "Gobierno",
    address: "Carrera 65 con Calle 42",
    aliases: ["comisaria de familia porvenir", "family commissioner office"],
  },
  {
    name: "Centro de Monitoreo y Control (CMC)",
    category: "Seguridad",
    address: "Carrera 54",
    area: "Via Juan de Dios Morales",
    aliases: ["cmc", "centro de monitoreo y control"],
  },
  {
    name: "Oficina de Pasaportes (Sede Enlace)",
    category: "Gobierno",
    address: "Transversal 24 # 42-121",
    area: "Reserva Plaza",
    aliases: ["pasaportes", "passport office"],
  },
  {
    name: "DIAN",
    category: "Gobierno",
    address: "Aeropuerto JMC",
    aliases: ["dian", "tax authority"],
  },
  {
    name: "Gaula Militar Oriente",
    category: "Seguridad",
    address: "Sector El Tablazo",
    aliases: ["gaula militar"],
  },
  {
    name: "Mall Terracina Llanogrande",
    category: "Comercio",
    address: "Km 10 Via Llanogrande",
    aliases: ["terracina"],
  },
  {
    name: "Mall La Morelia",
    category: "Comercio",
    address: "Sector El Tablazo",
    aliases: ["la morelia"],
  },
  {
    name: "Euro Supermercados (Llanogrande)",
    category: "Comercio",
    address: "Mall Jardines",
    aliases: ["euro llanogrande", "euro supermercados"],
  },
  {
    name: "Carulla Llanogrande",
    category: "Comercio",
    address: "Km 8 Via Llanogrande",
    aliases: ["carulla"],
  },
  {
    name: "Exito Rionegro (Centro)",
    category: "Comercio",
    address: "Calle 49 # 49-16",
    aliases: ["exito centro", "exito rionegro"],
  },
  {
    name: "Exito San Nicolas",
    category: "Comercio",
    address: "Interior C.C. San Nicolas",
    aliases: ["exito san nicolas"],
  },
  {
    name: "Jumbo Rionegro",
    category: "Comercio",
    address: "C.C. Savanna Plaza",
    aliases: ["jumbo"],
  },
  {
    name: "Decathlon Rionegro",
    category: "Comercio",
    address: "Sector El Porvenir",
    aliases: ["decathlon"],
  },
  {
    name: "Homecenter / Constructor",
    category: "Comercio",
    address: "Via Rionegro - Llanogrande",
    area: "Sector Gualanday",
    aliases: ["homecenter", "constructor"],
  },
  {
    name: "Makro Rionegro",
    category: "Comercio",
    address: "Autopista Medellin - Bogota",
    area: "Retorno Belen",
    aliases: ["makro"],
  },
  {
    name: "Alkosto Rionegro",
    category: "Comercio",
    address: "Sector Savanna Plaza",
    aliases: ["alkosto"],
  },
  {
    name: "Mall Milla de Oro",
    category: "Comercio",
    address: "Via Don Diego - Llanogrande",
    aliases: ["milla de oro"],
  },
  {
    name: "Comercializadora Gualanday",
    category: "Comercio",
    address: "Carrera 55A # 29-10",
    aliases: ["gualanday"],
  },
  {
    name: "Universidad Catolica de Oriente (UCO)",
    category: "Educacion",
    address: "Sector San Antonio",
    aliases: ["uco", "universidad catolica de oriente"],
  },
  {
    name: "Universidad de Antioquia (Sede Oriente)",
    category: "Educacion",
    address: "El Carmen de Viboral - Via Rionegro",
    aliases: ["universidad de antioquia oriente", "udea oriente"],
  },
  {
    name: "Colegio San Ignacio de Loyola (Sede Llanogrande)",
    category: "Educacion",
    address: "Km 6 Via Llanogrande",
    aliases: ["san ignacio de loyola"],
  },
  {
    name: "Colegio The Columbus School",
    category: "Educacion",
    address: "Alto de las Palmas",
    area: "Via Llanogrande",
    aliases: ["columbus school"],
  },
  {
    name: "Colegio Monsenor Alfonso Uribe Jaramillo",
    category: "Educacion",
    address: "Sector UCO",
    aliases: ["monsenor alfonso uribe jaramillo"],
  },
  {
    name: "Institucion Educativa Julio Sanin",
    category: "Educacion",
    address: "Carrera 48 # 49-64",
    aliases: ["julio sanin"],
  },
  {
    name: "Institucion Educativa Baldomero Sanin Cano",
    category: "Educacion",
    address: "Carrera 52",
    aliases: ["baldomero sanin cano"],
  },
  {
    name: "ASDI (Institucion Tecnica)",
    category: "Educacion",
    address: "Calle 50 # 50-32",
    aliases: ["asdi"],
  },
  {
    name: "Somer Inc (Cancerologia)",
    category: "Salud",
    address: "Calle 38 # 54A-35",
    aliases: ["somer inc", "cancerologia somer"],
  },
  {
    name: "Laboratorio Departamental (Sede Oriente)",
    category: "Salud",
    address: "Cerca al Hospital San Juan de Dios",
    aliases: ["laboratorio departamental oriente"],
  },
  {
    name: "Promedan IPS",
    category: "Salud",
    address: "Calle 43 # 52-25",
    aliases: ["promedan"],
  },
  {
    name: "Sura Salud Familiar",
    category: "Salud",
    address: "Mall Reserva Plaza",
    aliases: ["sura salud familiar"],
  },
  {
    name: "Centro Medico San Vicente Fundacion",
    category: "Salud",
    address: "Via Llanogrande",
    area: "Vereda Chipre",
    aliases: ["centro medico san vicente"],
  },
  {
    name: "OralHome (Clinica Odontologica)",
    category: "Salud",
    address: "C.C. San Nicolas",
    aliases: ["oralhome"],
  },
  {
    name: "EPS Sanitas (Centro Medico)",
    category: "Salud",
    address: "Sector El Porvenir",
    aliases: ["sanitas", "eps sanitas"],
  },
  {
    name: "Reposteria El Tranvia",
    category: "Gastronomia",
    address: "San Antonio de Pereira",
    aliases: ["el tranvia"],
  },
  {
    name: "Mundo Dulce",
    category: "Gastronomia",
    address: "Parque de San Antonio",
    aliases: ["mundo dulce"],
  },
  {
    name: "Restaurante Dona Rosa",
    category: "Gastronomia",
    address: "Km 9 Via Llanogrande",
    aliases: ["dona rosa"],
  },
  {
    name: "Crepes & Waffles",
    category: "Gastronomia",
    address: "C.C. San Nicolas / Mall Jardines",
    aliases: ["crepes and waffles"],
  },
  {
    name: "Il Forno",
    category: "Gastronomia",
    address: "Mall Llanogrande",
    aliases: ["il forno"],
  },
  {
    name: "Restaurante El Rancherito",
    category: "Gastronomia",
    address: "Km 11 Via Llanogrande",
    aliases: ["el rancherito"],
  },
  {
    name: "Hato Viejo",
    category: "Gastronomia",
    address: "Mall Reserva Plaza",
    aliases: ["hato viejo"],
  },
  {
    name: "Chef Burger",
    category: "Gastronomia",
    address: "Mall Jardines de Llanogrande",
    aliases: ["chef burger"],
  },
  {
    name: "Vereda El Tablazo",
    category: "Sector",
    address: "Zona rural integrada de Rionegro",
    aliases: ["el tablazo"],
  },
  {
    name: "Vereda Vilachuaga",
    category: "Sector",
    address: "Zona rural integrada de Rionegro",
    aliases: ["vilachuaga"],
  },
  {
    name: "Vereda Las Loma",
    category: "Sector",
    address: "Zona residencial de alta densidad",
    aliases: ["las loma"],
  },
  {
    name: "Vereda Abreo",
    category: "Sector",
    address: "Entrada norte a Rionegro",
    aliases: ["abreo"],
  },
  {
    name: "Vereda Cuchillas",
    category: "Sector",
    address: "Zona de bodegas y logistica",
    aliases: ["cuchillas"],
  },
  {
    name: "Vereda Chipre",
    category: "Sector",
    address: "Zona de infraestructura de salud privada",
    aliases: ["chipre"],
  },
  {
    name: "Barrio El Porvenir",
    category: "Sector",
    address: "Etapas 1 a 6",
    aliases: ["el porvenir"],
  },
  {
    name: "Urbanizacion Cuatro Esquinas",
    category: "Sector",
    address: "Sector comercial popular de alta afluencia",
    aliases: ["cuatro esquinas"],
  },
  {
    name: "Barrio Alto de la Capilla",
    category: "Sector",
    address: "Zona historica",
    aliases: ["alto de la capilla"],
  },
  {
    name: "Barrio Quebrada Arriba",
    category: "Sector",
    address: "Zona de talleres y comercio automotriz",
    aliases: ["quebrada arriba"],
    tags: ["mechanic_zone", "car_repair", "automotive_service"],
  },
  {
    name: "Oficina de Catastro Municipal",
    category: "Gobierno",
    address: "Carrera 50 # 49 - 05",
    area: "Palacio Municipal",
    aliases: ["catastro", "cadastre office"],
    tags: ["cadastre", "institutional_services", "procedures"],
    openingHoursEs: "Horario institucional general: lunes a jueves de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 5:00 p.m.; viernes de 7:00 a.m. a 12:00 m. y de 1:00 p.m. a 4:00 p.m.",
    openingHoursEn: "General institutional hours: Monday to Thursday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 5:00 p.m.; Friday from 7:00 a.m. to 12:00 p.m. and from 1:00 p.m. to 4:00 p.m.",
  },
  {
    name: "Subsecretaria de Gestion del Riesgo",
    category: "Gobierno",
    address: "Calle 52 # 50-15",
    area: "Antiguo Colegio Julio Sanin",
    aliases: ["gestion del riesgo", "risk management office"],
  },
  {
    name: "Comisaria de Familia (Sede Centro)",
    category: "Gobierno",
    address: "Calle 51 # 48-35",
    aliases: ["comisaria de familia centro"],
  },
  {
    name: "Oficina de Estratificacion",
    category: "Gobierno",
    address: "Carrera 50 # 49 - 05, Piso 1",
    aliases: ["estratificacion"],
  },
  {
    name: "Archivo Municipal de Rionegro",
    category: "Gobierno",
    address: "Carrera 47 # 51-67",
    aliases: ["archivo municipal"],
  },
  {
    name: "Cuerpo de Bomberos (Estacion Llanogrande)",
    category: "Emergencias",
    address: "Cerca al Hospital San Vicente Fundacion",
    aliases: ["bomberos llanogrande"],
  },
  {
    name: "Inspeccion de Policia Sur",
    category: "Seguridad",
    address: "Sector San Antonio de Pereira",
    aliases: ["inspeccion de policia sur"],
  },
  {
    name: "Casa de Justicia de Rionegro",
    category: "Justicia",
    address: "Carrera 65 # 42-121",
    area: "El Porvenir",
    aliases: ["casa de justicia"],
  },
  {
    name: "Oficina de Sisben",
    category: "Gobierno",
    address: "Calle 52 # 50-15",
    area: "Julio Sanin",
    aliases: ["sisben"],
    tags: ["citizen_services", "institutional_services", "procedures"],
  },
  {
    name: "Secretaria de Desarrollo Territorial",
    category: "Gobierno",
    address: "Carrera 54 # 56-162",
    aliases: ["desarrollo territorial"],
  },
  {
    name: "Oficina de Atencion a Victimas",
    category: "Gobierno",
    address: "Calle 51 con Carrera 48",
    aliases: ["atencion a victimas", "victims office"],
  },
  {
    name: "Sede Operativa Movilidad (Transito)",
    category: "Gobierno",
    address: "Carrera 47 # 62-50",
    aliases: ["sede operativa movilidad", "transito operativo"],
  },
  {
    name: "IPS Universitaria (Sede Rionegro)",
    category: "Salud",
    address: "Calle 43 # 52-40",
    aliases: ["ips universitaria"],
  },
  {
    name: "Laboratorio Medico Las Americas",
    category: "Salud",
    address: "C.C. San Nicolas",
    aliases: ["laboratorio las americas"],
  },
  {
    name: "Centro Medico Sanitas Rionegro",
    category: "Salud",
    address: "Carrera 55A # 35-227",
    area: "Savanna Plaza",
    aliases: ["centro medico sanitas"],
  },
  {
    name: "Unidad Prestadora de Salud San Antonio",
    category: "Salud",
    address: "Carrera 55",
    area: "San Antonio",
    aliases: ["ups san antonio"],
  },
  {
    name: "IPS Comfama Rionegro",
    category: "Salud",
    address: "Calle 51 # 48-35",
    aliases: ["ips comfama"],
  },
  {
    name: "Optica Santa Lucia (Llanogrande)",
    category: "Salud",
    address: "Mall Jardines",
    aliases: ["optica santa lucia"],
  },
  {
    name: "Drogueria Colsubsidio (Llanogrande)",
    category: "Salud",
    address: "Mall Complex",
    aliases: ["colsubsidio llanogrande"],
  },
  {
    name: "Farmacia Pasteur (San Antonio)",
    category: "Salud",
    address: "Parque Principal de San Antonio",
    aliases: ["farmacia pasteur"],
  },
  {
    name: "Laboratorio Departamental de Salud",
    category: "Salud",
    address: "Carrera 48",
    area: "Sector Hospital",
    aliases: ["laboratorio departamental de salud"],
  },
  {
    name: "Centro de Especialistas de Oriente",
    category: "Salud",
    address: "Calle 38 # 54A-35",
    aliases: ["centro de especialistas de oriente"],
  },
  {
    name: "I.E. Josefina Munoz Gonzalez",
    category: "Educacion",
    address: "Calle 52 # 44-03",
    aliases: ["josefina munoz gonzalez"],
  },
  {
    name: "I.E. Escuela Normal Superior de Maria",
    category: "Educacion",
    address: "Carrera 52 # 30-48",
    aliases: ["escuela normal superior de maria"],
  },
  {
    name: "Liceo Jose Maria Cordoba",
    category: "Educacion",
    address: "Carrera 52 # 40-86",
    aliases: ["liceo jose maria cordoba"],
  },
  {
    name: "I.E. Tecnica Industrial Santiago de Arma",
    category: "Educacion",
    address: "Carrera 50 # 50-19",
    aliases: ["santiago de arma"],
  },
  {
    name: "I.E. Concejo Municipal El Porvenir",
    category: "Educacion",
    address: "Carrera 65A # 75A-01",
    aliases: ["concejo municipal el porvenir"],
  },
  {
    name: "Colegio San Jose Obrero",
    category: "Educacion",
    address: "Calle 59 # 38-55",
    aliases: ["san jose obrero"],
  },
  {
    name: "Colegio Campestre Horizontes",
    category: "Educacion",
    address: "Km 4 Via Llanogrande",
    aliases: ["campestre horizontes"],
  },
  {
    name: "Colegio Triangulo",
    category: "Educacion",
    address: "Calle 34 # 59-113",
    aliases: ["colegio triangulo"],
  },
  {
    name: "Colegio Montessori (Sede Oriente)",
    category: "Educacion",
    address: "Vereda Cabeceras",
    aliases: ["montessori oriente"],
  },
  {
    name: "Colegio The Victoria School",
    category: "Educacion",
    address: "Via Llanogrande - Don Diego",
    aliases: ["the victoria school"],
  },
  {
    name: "Politecnico Jaime Isaza Cadavid (Sede Rionegro)",
    category: "Educacion",
    address: "Carrera 50 # 49-05",
    area: "Area administrativa",
    aliases: ["politecnico jaime isaza", "jaime isaza cadavid"],
  },
  {
    name: "Centro de Formacion Censa",
    category: "Educacion",
    address: "Calle 51 # 46-72",
    aliases: ["censa"],
  },
  {
    name: "Bancolombia (Sucursal Llanogrande)",
    category: "Servicios",
    address: "Mall Jardines de Llanogrande",
    aliases: ["bancolombia llanogrande"],
  },
  {
    name: "Banco de Bogota (Sede Centro)",
    category: "Servicios",
    address: "Calle 49 # 50-24",
    aliases: ["banco de bogota"],
  },
  {
    name: "Davivienda (C.C. San Nicolas)",
    category: "Servicios",
    address: "Calle 43 # 54-139",
    aliases: ["davivienda san nicolas"],
  },
  {
    name: "Banco AV Villas",
    category: "Servicios",
    address: "Savanna Plaza",
    aliases: ["av villas"],
  },
  {
    name: "Coopetraban (Sede Rionegro)",
    category: "Servicios",
    address: "Calle 51 # 50-42",
    aliases: ["coopetraban"],
  },
  {
    name: "Mall Llanogrande Plaza",
    category: "Comercio",
    address: "Km 8 Via Rionegro",
    aliases: ["llanogrande plaza"],
  },
  {
    name: "Mall El Tablazo",
    category: "Comercio",
    address: "Sector Aeropuerto",
    aliases: ["mall el tablazo"],
  },
  {
    name: "Mall Indiana",
    category: "Comercio",
    address: "Alto de las Palmas",
    area: "Sector Palmas - Llanogrande",
    aliases: ["mall indiana", "indiana mall"],
  },
  {
    name: "Supermercado La Vaquita",
    category: "Comercio",
    address: "Sector El Porvenir",
    aliases: ["la vaquita"],
  },
  {
    name: "D1 (Llanogrande)",
    category: "Comercio",
    address: "Cerca al Complex",
    aliases: ["d1 llanogrande"],
  },
  {
    name: "Mercado de Oriente",
    category: "Comercio",
    address: "Carrera 46 # 47-80",
    area: "Plaza de mercado central",
    aliases: ["mercado de oriente", "central market"],
  },
  {
    name: "Catedral de San Nicolas el Magno",
    category: "Turismo",
    address: "Parque Principal de Rionegro",
    aliases: ["catedral de san nicolas", "cathedral"],
  },
  {
    name: "Iglesia de San Antonio de Pereira",
    category: "Turismo",
    address: "Parque de San Antonio",
    aliases: ["iglesia de san antonio"],
  },
  {
    name: "Parroquia El Espiritu Santo",
    category: "Turismo",
    address: "Barrio El Porvenir",
    aliases: ["espiritu santo"],
  },
  {
    name: "Iglesia de Nuestra Senora de Chiquinquira",
    category: "Turismo",
    address: "Barrio Alto de la Capilla",
    aliases: ["chiquinquira"],
  },
  {
    name: "Parroquia Sagrado Corazon de Jesus",
    category: "Turismo",
    address: "Sector Cuatro Esquinas",
    aliases: ["sagrado corazon de jesus"],
  },
  {
    name: "Capilla del Hospital San Juan de Dios",
    category: "Turismo",
    address: "Carrera 48",
    aliases: ["capilla del hospital"],
  },
  {
    name: "Restaurante San Carbon (Llanogrande)",
    category: "Gastronomia",
    address: "Km 8 Via Rionegro",
    aliases: ["san carbon"],
  },
  {
    name: "Hamburguesas El Corral (Savanna)",
    category: "Gastronomia",
    address: "C.C. Savanna Plaza",
    aliases: ["el corral savanna"],
  },
  {
    name: "Starbucks (Mall Jardines)",
    category: "Gastronomia",
    address: "Km 9 Via Llanogrande",
    aliases: ["starbucks"],
  },
  {
    name: "Pizzeria Olivia",
    category: "Gastronomia",
    address: "Mall Complex Llanogrande",
    aliases: ["olivia"],
  },
  {
    name: "Restaurante Blasina",
    category: "Gastronomia",
    address: "Km 7 Via Llanogrande",
    aliases: ["blasina"],
  },
  {
    name: "Vivero Tierra Negra",
    category: "Gastronomia",
    address: "Via Rionegro - Llanogrande",
    aliases: ["tierra negra"],
  },
  {
    name: "Secretaria de Desarrollo Economico",
    category: "Gobierno",
    address: "Calle 49 # 50-05",
    aliases: ["desarrollo economico"],
    tags: ["employment", "institutional_services", "procedures"],
  },
  {
    name: "Secretaria de Cultura",
    category: "Gobierno",
    address: "Carrera 50 entre calles 48 y 49",
    aliases: ["cultura"],
  },
  {
    name: "Secretaria de Medioambiente y Habitat",
    category: "Gobierno",
    address: "Calle 52 # 50-15",
    area: "Sede Julio Sanin",
    aliases: ["medioambiente", "habitat", "environment office"],
  },
  {
    name: "Secretaria de Infraestructura",
    category: "Gobierno",
    address: "Calle 49 # 50-05, Piso 2",
    aliases: ["infraestructura", "infrastructure office"],
  },
  {
    name: "Secretaria de Seguridad y Justicia",
    category: "Gobierno",
    address: "Calle 52 # 50-15",
    aliases: ["seguridad y justicia"],
  },
  {
    name: "Secretaria de Educacion (Sede Administrativa)",
    category: "Gobierno",
    address: "Carrera 48 # 49-64",
    aliases: ["secretaria de educacion", "education office"],
    tags: ["education", "institutional_services", "procedures"],
  },
  {
    name: "Oficina de Valorizacion",
    category: "Gobierno",
    address: "Calle 49 # 50-05",
    aliases: ["valorizacion"],
    tags: ["taxes", "institutional_services", "procedures"],
  },
  {
    name: "Oficina de Rentas Municipales",
    category: "Gobierno",
    address: "Palacio Municipal, primer piso",
    aliases: ["rentas municipales", "municipal taxes office"],
    tags: ["taxes", "institutional_services", "procedures"],
  },
  {
    name: "Centro de Bienestar del Anciano (CBA) San Jose",
    category: "Servicios",
    address: "Sector San Antonio",
    aliases: ["cba san jose"],
  },
  {
    name: "Casa Provincial de Rionegro (Sede Administrativa)",
    category: "Gobierno",
    address: "Calle 51 La Convencion",
    aliases: ["casa provincial"],
  },
  {
    name: "Inspeccion de Policia El Porvenir",
    category: "Seguridad",
    address: "Carrera 65 # 42-121",
    aliases: ["inspeccion de policia el porvenir"],
  },
  {
    name: "Comando Distrito Seis de Policia",
    category: "Seguridad",
    address: "Carrera 70 # 44-25",
    area: "El Porvenir",
    aliases: ["distrito seis de policia", "police district six"],
  },
  {
    name: "Subestacion de Policia Llanogrande",
    category: "Seguridad",
    address: "Vereda Tres Puertas",
    area: "Via Don Diego",
    aliases: ["subestacion de policia llanogrande"],
  },
  {
    name: "CAI Aeropuerto JMC",
    category: "Seguridad",
    address: "Terminal de pasajeros, segundo nivel",
    aliases: ["cai aeropuerto", "airport police post"],
  },
  {
    name: "CAI San Antonio de Pereira",
    category: "Seguridad",
    address: "Entrada principal sector gastronomico",
    aliases: ["cai san antonio"],
  },
  {
    name: "CAI Cuatro Esquinas",
    category: "Seguridad",
    address: "Sector comercial popular",
    aliases: ["cai cuatro esquinas"],
  },
  {
    name: "Cuerpo de Bomberos (Sede Porvenir)",
    category: "Emergencias",
    address: "Calle 42 con Carrera 65",
    aliases: ["bomberos porvenir"],
  },
  {
    name: "I.E. Barro Blanco",
    category: "Educacion",
    address: "Km 4 Via Aeropuerto JMC",
    aliases: ["barro blanco"],
  },
  {
    name: "I.E. Ana Gomez de Sierra",
    category: "Educacion",
    address: "Km 34 Vereda La Playa",
    aliases: ["ana gomez de sierra"],
  },
  {
    name: "I.E. Baltazar Salazar",
    category: "Educacion",
    address: "Vereda Pontezuela",
    aliases: ["baltazar salazar"],
  },
  {
    name: "I.E. Cuchillas de San Jose",
    category: "Educacion",
    address: "Vereda Cuchillas",
    aliases: ["cuchillas de san jose"],
  },
  {
    name: "I.E. Domingo Savio",
    category: "Educacion",
    address: "Vereda Guayabito",
    area: "Via El Retiro",
    aliases: ["domingo savio"],
  },
  {
    name: "I.E. Gilberto Echeverri Mejia",
    category: "Educacion",
    address: "Vereda Cabeceras",
    aliases: ["gilberto echeverri mejia"],
  },
  {
    name: "I.E. Guillermo Gaviria Correa",
    category: "Educacion",
    address: "Vereda Yarumal",
    aliases: ["guillermo gaviria correa"],
  },
  {
    name: "Colegio Gimnasio Vermont (Sede Oriente)",
    category: "Educacion",
    address: "Vereda El Tablazo",
    aliases: ["gimnasio vermont", "vermont"],
  },
  {
    name: "Hotel Movich Las Lomas",
    category: "Hotel",
    address: "Sector Aeropuerto",
    area: "Glorieta externa",
    aliases: ["movich las lomas", "movich"],
  },
  {
    name: "Hotel Lagoon Llanogrande",
    category: "Hotel",
    address: "Km 13.8 Via JMC",
    area: "Vereda El Tablazo",
    aliases: ["lagoon llanogrande", "hotel lagoon"],
  },
  {
    name: "Hotel Dann Carlton Rionegro",
    category: "Hotel",
    address: "Autopista Medellin - Bogota",
    area: "Sector Belen",
    aliases: ["dann carlton"],
  },
  {
    name: "Hotel Las Margaritas",
    category: "Hotel",
    address: "Carrera 50 # 52-25",
    area: "Centro",
    aliases: ["las margaritas"],
  },
  {
    name: "Hotel CSI Llanogrande",
    category: "Hotel",
    address: "Km 6.4 Via Don Diego",
    aliases: ["csi llanogrande"],
  },
  {
    name: "MG Hotels and Suites",
    category: "Hotel",
    address: "Sector Savanna Plaza",
    aliases: ["mg hotels", "mg hotels and suites"],
  },
  {
    name: "Aparthotel Travelers Rio Verde",
    category: "Hotel",
    address: "Sector El Tablazo",
    aliases: ["travelers rio verde"],
  },
  {
    name: "Finca Hotel La Ponderosa",
    category: "Hotel",
    address: "Vereda Las Loma",
    aliases: ["la ponderosa"],
  },
  {
    name: "Hotel Valeriana",
    category: "Hotel",
    address: "San Antonio de Pereira",
    aliases: ["valeriana"],
  },
  {
    name: "Parque de los Martires",
    category: "Espacio publico",
    address: "Carrera 50 entre calles 51 y 52",
    aliases: ["parque de los martires"],
  },
  {
    name: "Parque Liborio Mejia",
    category: "Espacio publico",
    address: "Contiguo a la Parroquia de Jesus Nazareno",
    aliases: ["liborio mejia"],
  },
  {
    name: "Parque Colina del Cementerio",
    category: "Espacio publico",
    address: "Calle 51 con Carrera 54",
    aliases: ["colina del cementerio"],
  },
  {
    name: "Puente Real",
    category: "Espacio publico",
    address: "Via que conecta al Centro con El Porvenir",
    aliases: ["puente real"],
  },
  {
    name: "Puente Mejia",
    category: "Espacio publico",
    address: "Antiguo paso historico sobre el Rio Negro",
    aliases: ["puente mejia"],
  },
  {
    name: "Mausoleo de Juan del Corral",
    category: "Turismo",
    address: "Cripta de la Catedral de San Nicolas",
    aliases: ["mausoleo de juan del corral"],
  },
  {
    name: "Escultura Ecuestre de Jose Maria Cordova",
    category: "Turismo",
    address: "Centro del Parque Principal",
    aliases: ["escultura ecuestre", "statue of jose maria cordova"],
  },
  {
    name: "Plaza de Ferias de Rionegro",
    category: "Espacio publico",
    address: "Sector Quebrada Arriba",
    aliases: ["plaza de ferias"],
  },
  {
    name: "DollarCity (Llanogrande)",
    category: "Comercio",
    address: "Mall Jardines de Llanogrande",
    aliases: ["dollarcity llanogrande"],
  },
  {
    name: "Gimnasio Action Black (Llanogrande)",
    category: "Servicios",
    address: "Complex Llanogrande",
    aliases: ["action black"],
  },
  {
    name: "Farmatodo Llanogrande",
    category: "Salud",
    address: "Km 8 Via Rionegro",
    aliases: ["farmatodo llanogrande"],
  },
  {
    name: "Crepes & Waffles Heladeria",
    category: "Gastronomia",
    address: "Mall Llanogrande",
    aliases: ["crepes heladeria"],
  },
  {
    name: "Juan Valdez Cafe",
    category: "Gastronomia",
    address: "Interior Aeropuerto JMC y Mall Jardines",
    aliases: ["juan valdez"],
  },
  {
    name: "Autolarte Rionegro",
    category: "automotive_service",
    address: "Via Rionegro - Llanogrande",
    area: "Corredor comercial automotriz",
    aliases: ["autolarte", "autolarte rionegro", "taller autolarte"],
    tags: ["car_repair", "automotive_service", "dealership", "mechanic"],
  },
  {
    name: "Sector Belchite (talleres automotrices)",
    category: "mechanic_zone",
    address: "Sector Belchite",
    aliases: ["belchite", "talleres belchite", "sector belchite"],
    tags: ["car_repair", "mechanic_zone", "automotive_service", "taller"],
  },
  {
    name: "Corredor automotriz Via Llanogrande",
    category: "dealership",
    address: "Via Rionegro - Llanogrande",
    aliases: ["concesionarios via llanogrande", "via llanogrande", "llanogrande dealerships"],
    tags: ["dealership", "automotive_service", "car_repair", "concesionario"],
  },
];

export function buildPlaceSearchText(place: OfficialPlace) {
  return [
    place.name,
    place.category,
    place.address,
    place.area ?? "",
    ...(place.aliases ?? []),
    ...(place.tags ?? []),
  ]
    .join(" ")
    .trim();
}
